const DEFAULT_TOPICS=[
 {name:'台灣軍事',query:'Taiwan military'},
 {name:'台海情勢',query:'"Taiwan Strait" OR "cross-strait"'},
 {name:'共軍動態',query:'PLA OR "People’s Liberation Army"'},
 {name:'軍售合作',query:'("arms sale" OR "defense cooperation") Taiwan'},
 {name:'灰色地帶',query:'("gray zone" OR "grey zone") Taiwan'}
];

const savedSettings=(()=>{try{return JSON.parse(localStorage.getItem('echoSettings'))||{}}catch{return{}}})();
const isFileMode=location.protocol==='file:';
let pageSize=Number(savedSettings.pageSize)||5,articles=[],visible=pageSize,sourceFilter='',topicRanking=[],isSearching=false;
const list=document.querySelector('#articleList'),statusBox=document.querySelector('#status');
const today=new Date(),weekAgo=new Date(today); weekAgo.setDate(today.getDate()-(Number(savedSettings.days)||30));
const iso=d=>d.toISOString().slice(0,10);
document.querySelector('#dateTo').value=iso(today); document.querySelector('#dateFrom').value=iso(weekAgo);
const fmtDate=value=>{if(!value)return'時間未註明';const s=String(value).replace(/[^0-9]/g,'');if(s.length<8)return value;const d=new Date(`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T${s.slice(8,10)||'00'}:${s.slice(10,12)||'00'}:00Z`);const h=Math.floor(Math.max(0,Date.now()-d)/36e5);return h<1?'剛剛':h<24?`${h} 小時前`:`${Math.floor(h/24)} 天前`};
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ymd=value=>{const s=String(value||'').replace(/[^0-9]/g,'');return s.length>=8?`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}`:''};
function renderVolume(){
  const from=document.querySelector('#dateFrom').value,to=document.querySelector('#dateTo').value;
  const days=[],cursor=new Date(from+'T00:00:00Z'),last=new Date(to+'T00:00:00Z');while(cursor<=last&&days.length<93){days.push(iso(cursor));cursor.setUTCDate(cursor.getUTCDate()+1)}
  const counts=Object.fromEntries(days.map(d=>[d,0]));articles.forEach(a=>{const d=ymd(a.seen);if(d in counts)counts[d]++});
  const values=days.map(d=>counts[d]),peak=Math.max(1,...values);document.querySelector('#peakValue').textContent=Math.max(...values);
  document.querySelector('#volumeChart').innerHTML=days.map((d,i)=>`<div class="bar-day"><i style="--h:${Math.max(4,values[i]/peak*76)}%"><b>${values[i]}</b></i><span>${d.slice(5).replace('-','/')}</span></div>`).join('');
  document.querySelector('#rangeCaption').textContent=`${days.length} 天搜尋區間`;
  const half=Math.ceil(values.length/2),old=values.slice(0,half).reduce((a,b)=>a+b,0),recent=values.slice(half).reduce((a,b)=>a+b,0),delta=old?Math.round((recent-old)/old*100):recent?100:0;
  const trend=document.querySelector('#volumeTrend');trend.textContent=`${delta>=0?'↗':'↘'} ${Math.abs(delta)}%`;trend.className=`trend ${delta>=0?'up':'warn'}`;
}
const TOPIC_RULES=[
 {name:'台海與台灣安全',pattern:/taiwan|taiwan strait|cross-strait/i},
 {name:'中共解放軍動態',pattern:/\bpla\b|people.?s liberation army|chinese military|china military/i},
 {name:'無人機與不對稱戰力',pattern:/drone|unmanned|asymmetric|loitering munition/i},
 {name:'軍售與國防合作',pattern:/arms? sale|weapons? sale|defen[cs]e cooperation|military aid|security assistance/i},
 {name:'軍演與印太行動',pattern:/exercise|drill|indo-pacific|joint operation|deployment/i}
];
function renderTopicInsights(){
 topicRanking=TOPIC_RULES.map(rule=>({name:rule.name,matches:articles.filter(a=>rule.pattern.test(`${a.title} ${(a.tags||[]).join(' ')}`))})).filter(x=>x.matches.length).sort((a,b)=>b.matches.length-a.matches.length).slice(0,4);
 const host=document.querySelector('#topicInsights'),max=topicRanking[0]?.matches.length||1;
 host.innerHTML=topicRanking.length?topicRanking.map((item,i)=>`<button class="topic topic-button" data-topic-index="${i}"><div><b>${String(i+1).padStart(2,'0')}</b><span><strong>${esc(item.name)}</strong><small>${item.matches.length} 則相關新聞 · 點擊查看</small></span></div><em style="--w:${item.matches.length/max*100}%"></em></button>`).join(''):'<p class="modal-note">本次結果尚無可歸類議題。</p>';
 host.querySelectorAll('[data-topic-index]').forEach(button=>button.onclick=()=>openTopicArticles(Number(button.dataset.topicIndex)));
}
function openTopicArticles(index){const item=topicRanking[index];if(!item)return;document.querySelector('#topicArticlesTitle').textContent=`${item.name}（${item.matches.length}）`;document.querySelector('#topicArticlesContent').innerHTML=[...item.matches].sort((a,b)=>String(b.seen).localeCompare(String(a.seen))).map(a=>`<div class="saved-article"><div><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a><small>${esc(a.domain)} · ${fmtDate(a.seen)}</small></div><a class="original-link" href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">原文 ↗</a></div>`).join('');openModal('topicArticlesModal')}
function updateStats(){const sources=new Set(articles.map(a=>a.domain).filter(Boolean)),activeDays=new Set(articles.map(a=>ymd(a.seen)).filter(Boolean));document.querySelector('#articleCount').textContent=articles.length;document.querySelector('#countryCount').textContent=activeDays.size;document.querySelector('#sourceCount').textContent=sources.size;renderVolume();renderCoverage();renderTopicInsights()}
function render(){
 const data=[...articles].filter(a=>!sourceFilter||a.domain===sourceFilter).sort((a,b)=>String(b.seen).localeCompare(String(a.seen))),savedUrls=new Set(getSaved().map(a=>a.url));
 list.innerHTML=data.slice(0,visible).map(a=>{const initial=esc((a.domain||'N')[0]),image=a.image?`<img class="thumb" src="${esc(a.image)}" alt="" onerror="this.outerHTML='<div class=&quot;thumb fallback-thumb&quot;>ECHO</div>'">`:`<div class="thumb fallback-thumb">${initial}</div>`,marked=savedUrls.has(a.url),translated=a.translation?`<div class="translation-result"><b>繁中標題</b><strong>${esc(a.translation)}</strong><b>免費重點</b><p>${esc(a.summary)}</p></div>`:`<button class="translate-btn" data-translate-url="${esc(a.url)}">免費翻譯重點</button>`;return `<article class="news-card"><div><div class="news-meta"><span class="source-logo">${initial}</span><strong>${esc(a.domain||'ENGLISH MEDIA')}</strong><span class="verified-source">✓ 外國新聞媒體</span><span>•</span><span>${fmtDate(a.seen)}</span><span class="lang">英文</span></div><h3><a href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">${esc(a.title)}</a></h3><p>來自外國英語新聞媒體；原文連結由 Google News 導向該媒體的官方文章。</p>${translated}<div class="news-foot">${(a.tags||['英語媒體',a.country]).filter(Boolean).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<a class="original-link" href="${esc(a.url)}" target="_blank" rel="noopener noreferrer">閱讀官方原文 ↗</a>${a.publisherUrl?`<a class="publisher-link" href="${esc(a.publisherUrl)}" target="_blank" rel="noopener noreferrer">媒體官網 ↗</a>`:''}<button class="save ${marked?'active':''}" data-url="${esc(a.url)}" aria-label="加入重要標記">${marked?'★':'☆'}</button></div></div>${image}</article>`}).join('')||'<div class="empty-state">外國新聞媒體目前沒有符合條件的報導。</div>';
 document.querySelector('#loadMore').hidden=visible>=data.length;document.querySelectorAll('.save').forEach(btn=>btn.onclick=()=>toggleSaved(btn.dataset.url));document.querySelectorAll('[data-translate-url]').forEach(btn=>btn.onclick=()=>translateArticle(btn.dataset.translateUrl,btn));updateSavedCount();
}
async function translateArticle(url,button){const article=articles.find(a=>a.url===url);if(!article)return;button.disabled=true;button.textContent='翻譯中…';try{const res=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:article.title,source:article.domain})});const json=await res.json();if(!res.ok)throw Error(json.error||`HTTP ${res.status}`);article.translation=json.translation;article.summary=json.summary;render()}catch(err){button.disabled=false;button.textContent='稍後重試';toast('免費翻譯暫時無法使用')}}
function validateRange(){const from=document.querySelector('#dateFrom').value,to=document.querySelector('#dateTo').value;if(!from||!to||from>to){toast('日期範圍不正確：開始日期必須早於結束日期');return false}const days=(new Date(to)-new Date(from))/864e5;if(days>92){toast('新聞資料源單次搜尋最多支援約三個月');return false}return true}
function setSearchBusy(busy,query=''){isSearching=busy;document.querySelector('#loadingOverlay').hidden=!busy;document.querySelector('#loadingQuery').textContent=query?`正在搜尋「${query}」…`:'請稍候，正在掃描外國英語媒體…';document.querySelector('#searchBtn').disabled=busy;document.querySelectorAll('.topic-chip').forEach(button=>button.disabled=busy)}
async function search(query){if(isSearching){toast('上一個搜尋仍在進行中，請稍候');return}if(!validateRange())return;sourceFilter='';const from=document.querySelector('#dateFrom').value,to=document.querySelector('#dateTo').value;document.querySelector('#resultLabel').textContent=`「${query}」· ${from} 至 ${to} · 外國英語新聞媒體`;visible=10;if(isFileMode){statusBox.hidden=false;statusBox.textContent='目前是離線檔案預覽，無法連接新聞伺服器。請改用部署完成的 HTTPS 公開網址。';toast('請使用公開網址進行即時搜尋');return}setSearchBusy(true,query);try{const res=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,from,to})});const json=await res.json();if(!res.ok)throw Error(json.error||`HTTP ${res.status}`);const found=Array.isArray(json.articles)?json.articles:[],updated=json.fetchedAt?new Date(json.fetchedAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'}):'';articles=found.map(a=>({title:a.title,domain:(a.domain||'ENGLISH MEDIA').toUpperCase(),country:a.sourcecountry,language:'English',seen:a.seendate,url:a.url,publisherUrl:a.publisherUrl,image:a.socialimage,verifiedPublisher:a.verifiedPublisher,tags:[a.sourcecountry,'外國新聞媒體'].filter(Boolean)}));statusBox.hidden=false;statusBox.textContent=articles.length?`搜尋完成：${articles.length} 則外國英語新聞｜資料更新：${updated||'剛剛'}｜來源：${json.provider||'國際新聞索引'}`:`搜尋完成：0 則新聞｜資料更新：${updated||'剛剛'}。所選期間沒有符合條件的外國英語新聞，請嘗試放寬關鍵字或日期範圍。`;}catch(err){articles=[];statusBox.hidden=false;statusBox.textContent=`搜尋未完成：${err.message}。請稍後再試或調整搜尋條件。`;}finally{document.querySelector('#initialState').hidden=true;document.querySelector('#resultsArea').hidden=false;updateStats();render();setSearchBusy(false)}}
document.querySelector('#searchForm').addEventListener('submit',e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.trim();if(q)search(q)});document.querySelectorAll('.quick-filters .chip[data-query]').forEach(c=>c.onclick=()=>applyTopic(c));document.querySelector('#loadMore').onclick=()=>{visible+=pageSize;render()};function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function openWorkspace(){const q=document.querySelector('#searchInput').value;document.querySelector('#workspaceContent').innerHTML=`<div class="workspace-query"><small>目前查詢</small><code>${esc(q)}</code></div><h3>進階語法</h3><ul><li><code>AND</code>：兩個條件都要出現</li><li><code>OR</code>：任一條件即可</li><li><code>"完整詞組"</code>：精確搜尋</li><li><code>( )</code>：組合多個條件</li></ul><h3>來源規則</h3><p>只保留已列入可信清單的英語新聞媒體；每則結果提供官方文章入口及媒體官網。</p>`;openModal('workspaceModal')}
document.querySelector('#guideBtn').onclick=openWorkspace;document.querySelector('#copyQueryBtn').onclick=async()=>{try{await navigator.clipboard.writeText(document.querySelector('#searchInput').value);toast('目前查詢已複製')}catch{toast('瀏覽器未允許複製')}};document.querySelector('#applyDefenseQueryBtn').onclick=()=>{const q='("Taiwan military" OR "Taiwan Strait") AND (defense OR security)';document.querySelector('#searchInput').value=q;closeModal('workspaceModal');search(q)};

function applyTopic(button){if(isSearching){toast('搜尋進行中，完成後再切換主題');return}document.querySelectorAll('.quick-filters .chip').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector('#searchInput').value=button.dataset.query;search(button.dataset.query)}
function openModal(id){document.querySelector('#'+id).hidden=false}
function closeModal(id){document.querySelector('#'+id).hidden=true}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
document.querySelectorAll('.modal-backdrop').forEach(m=>m.onclick=e=>{if(e.target===m)m.hidden=true});

function getTopics(){try{const saved=JSON.parse(localStorage.getItem('echoTopicsV2'));if(!Array.isArray(saved))return DEFAULT_TOPICS.map(t=>({...t}));let changed=false;const migrated=saved.map(t=>{if(t?.name==='台灣軍事'&&t.query==='"Taiwan military" OR "Taiwan Strait"'){changed=true;return{...t,query:'Taiwan military'}}return t});if(changed)localStorage.setItem('echoTopicsV2',JSON.stringify(migrated));return migrated}catch{return DEFAULT_TOPICS.map(t=>({...t}))}}
function saveTopics(topics){localStorage.setItem('echoTopicsV2',JSON.stringify(topics))}
function renderTopics(){
 const topics=getTopics(),host=document.querySelector('#savedTopics'),chips=document.querySelector('#watchlists'),manage=document.querySelector('#manageTopicsBtn');
 document.querySelectorAll('.topic-chip').forEach(c=>c.remove());
 topics.forEach((t,i)=>{const chip=document.createElement('button');chip.className='chip topic-chip';chip.dataset.query=t.query;chip.textContent=t.name;chip.onclick=()=>applyTopic(chip);chips.insertBefore(chip,manage)});
 host.innerHTML=topics.length?topics.map((t,i)=>`<div class="saved-topic"><strong>${esc(t.name)}</strong><code>${esc(t.query)}</code><button data-use-topic="${i}">套用</button><button class="edit-topic" data-edit-topic="${i}">編輯</button><button class="delete-topic" data-delete-topic="${i}">刪除</button></div>`).join(''):'<p class="modal-note">目前沒有監測主題，可新增或還原預設。</p>';
 host.querySelectorAll('[data-use-topic]').forEach(b=>b.onclick=()=>{const t=getTopics()[Number(b.dataset.useTopic)];document.querySelector('#searchInput').value=t.query;closeModal('topicsModal');search(t.query)});
 host.querySelectorAll('[data-edit-topic]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.editTopic),t=getTopics()[i];document.querySelector('#topicEditIndex').value=String(i);document.querySelector('#topicName').value=t.name;document.querySelector('#topicQuery').value=t.query;document.querySelector('#topicSubmitBtn').textContent='儲存修改';document.querySelector('#topicName').focus()});
 host.querySelectorAll('[data-delete-topic]').forEach(b=>b.onclick=()=>{const list=getTopics();list.splice(Number(b.dataset.deleteTopic),1);saveTopics(list);renderTopics();toast('已刪除監測主題')});
 document.querySelector('#topicCount').textContent=topics.length;
}
document.querySelector('#topicForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#topicName').value.trim(),query=document.querySelector('#topicQuery').value.trim(),edit=document.querySelector('#topicEditIndex').value,topics=getTopics();if(!name||!query)return;if(edit==='')topics.push({name,query});else topics[Number(edit)]={name,query};saveTopics(topics);e.target.reset();document.querySelector('#topicEditIndex').value='';document.querySelector('#topicSubmitBtn').textContent='新增主題';renderTopics();toast(edit===''?'已新增監測主題':'已更新監測主題')};
document.querySelector('#resetTopicsBtn').onclick=()=>{saveTopics(DEFAULT_TOPICS.map(t=>({...t})));document.querySelector('#topicForm').reset();document.querySelector('#topicEditIndex').value='';document.querySelector('#topicSubmitBtn').textContent='新增主題';renderTopics();toast('已還原五個預設主題')};
document.querySelector('#manageTopicsBtn').onclick=()=>{renderTopics();openModal('topicsModal')};
document.querySelector('#topicsNav').onclick=e=>{e.preventDefault();renderTopics();openModal('topicsModal')};

function sourceCounts(){const map={};articles.forEach(a=>map[a.domain]=(map[a.domain]||0)+1);return Object.entries(map).sort((a,b)=>b[1]-a[1])}
function renderCoverage(){const rows=sourceCounts(),max=rows[0]?.[1]||1;document.querySelector('#sourceList').innerHTML=rows.slice(0,4).map(([name,count])=>`<div class="source-row"><span>${esc(name)}</span><div><i style="--w:${count/max*100}%"></i></div><b>${count}</b></div>`).join('')||'<p class="modal-note">搜尋後顯示來源。</p>'}
function openSources(e){if(e)e.preventDefault();const rows=sourceCounts(),max=rows[0]?.[1]||1;document.querySelector('#sourcesContent').innerHTML=rows.map(([name,count])=>`<div class="source-row"><span>${esc(name)}</span><div><i style="--w:${count/max*100}%"></i></div><b>${count}</b><button data-filter-source="${esc(name)}">只看此來源</button></div>`).join('')||'<div class="empty-state">尚無來源資料。</div>';document.querySelectorAll('[data-filter-source]').forEach(b=>b.onclick=()=>{sourceFilter=b.dataset.filterSource;visible=pageSize;closeModal('sourcesModal');document.querySelector('#resultLabel').innerHTML=`目前只看：${esc(sourceFilter)} <span class="filter-note">來源篩選</span>`;render()});openModal('sourcesModal')}
document.querySelector('#sourceNav').onclick=openSources;document.querySelector('#sourceViewAll').onclick=openSources;document.querySelector('#mobileSourcesBtn').onclick=openSources;document.querySelector('#clearSourceFilter').onclick=()=>{sourceFilter='';closeModal('sourcesModal');document.querySelector('#resultLabel').textContent='已顯示全部媒體來源';render()};

function getSaved(){try{return JSON.parse(localStorage.getItem('echoSaved'))||[]}catch{return[]}}
function saveSaved(items){localStorage.setItem('echoSaved',JSON.stringify(items))}
function updateSavedCount(){document.querySelector('#savedCount').textContent=getSaved().length}
function toggleSaved(url){const saved=getSaved(),index=saved.findIndex(a=>a.url===url);if(index>=0){saved.splice(index,1);toast('已移除重要標記')}else{const article=articles.find(a=>a.url===url);if(article){saved.push(article);toast('已加入重要標記')}}saveSaved(saved);render();if(!document.querySelector('#savedModal').hidden)renderSaved()}
function renderSaved(){const saved=getSaved();document.querySelector('#savedContent').innerHTML=saved.length?saved.map((a,i)=>`<div class="saved-article"><div><a href="${esc(a.url)}" target="_blank">${esc(a.title)}</a><small>${esc(a.domain)} · ${fmtDate(a.seen)}</small></div><button data-remove-saved="${i}">移除</button></div>`).join(''):'<div class="empty-state">尚未標記新聞。請點新聞卡片右下角的 ☆。</div>';document.querySelectorAll('[data-remove-saved]').forEach(b=>b.onclick=()=>{const list=getSaved();list.splice(Number(b.dataset.removeSaved),1);saveSaved(list);renderSaved();render()});updateSavedCount()}
function openSaved(e){if(e)e.preventDefault();renderSaved();openModal('savedModal')}
document.querySelector('#savedNav').onclick=openSaved;document.querySelector('#mobileSavedBtn').onclick=openSaved;

document.querySelector('#settingDays').value=String(Number(savedSettings.days)||30);document.querySelector('#settingPageSize').value=String(visible);
document.querySelector('#settingsNav').onclick=e=>{e.preventDefault();openModal('settingsModal')};document.querySelector('#mobileSettingsBtn').onclick=()=>openModal('settingsModal');
document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();const settings={days:Number(document.querySelector('#settingDays').value),pageSize:Number(document.querySelector('#settingPageSize').value)};localStorage.setItem('echoSettings',JSON.stringify(settings));pageSize=settings.pageSize;visible=pageSize;const from=new Date(today);from.setDate(today.getDate()-settings.days);document.querySelector('#dateFrom').value=iso(from);closeModal('settingsModal');updateStats();render();toast('設定已儲存並套用')};

function briefHTML(){const query=document.querySelector('#searchInput').value,from=document.querySelector('#dateFrom').value,to=document.querySelector('#dateTo').value,sources=new Set(articles.map(a=>a.domain)).size,top=[...articles].sort((a,b)=>String(b.seen).localeCompare(String(a.seen))).slice(0,10);return `<p><strong>監測條件：</strong>${esc(query)}<br><strong>期間：</strong>${esc(from)} 至 ${esc(to)}</p><div class="brief-summary"><div><strong>${articles.length}</strong><span>新聞篇數</span></div><div><strong>${sources}</strong><span>媒體來源</span></div><div><strong>${document.querySelector('#countryCount').textContent}</strong><span>有新聞日期</span></div><div><strong>${articles.filter(a=>a.url).length}</strong><span>可點原文</span></div></div><h3>最新新聞</h3><ol class="brief-list">${top.map(a=>`<li><a href="${esc(a.url)}" target="_blank">${esc(a.title)}</a><br><small>${esc(a.domain)} · ${fmtDate(a.seen)}</small></li>`).join('')}</ol>`}
function openBrief(e){if(e)e.preventDefault();document.querySelector('#briefContent').innerHTML=briefHTML();openModal('briefModal')}
document.querySelector('#briefBtn').onclick=openBrief;document.querySelector('#dailyBriefNav').onclick=openBrief;document.querySelector('#mobileBriefBtn').onclick=openBrief;
document.querySelector('#copyBriefBtn').onclick=async()=>{const text=document.querySelector('#briefContent').innerText;try{await navigator.clipboard.writeText(text);toast('簡報文字已複製')}catch{toast('瀏覽器未允許複製，請手動選取文字')}};
document.querySelector('#printBriefBtn').onclick=()=>{const w=window.open('','_blank');if(!w){toast('瀏覽器阻擋彈出視窗');return}w.document.write(`<html><head><title>ECHO Global 每日簡報</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px;line-height:1.6}a{color:#075f4e}.brief-summary{display:flex;gap:20px}.brief-summary div{padding:10px;background:#f2f7f5}</style></head><body><h1>ECHO Global 每日新聞簡報</h1>${briefHTML()}</body></html>`);w.document.close();w.print()};

document.querySelector('#homeNav').onclick=e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'});toast('已回到情報總覽')};
document.querySelector('#notificationBtn').onclick=()=>toast('目前沒有新的系統通知');
document.querySelector('#userMenuBtn').onclick=()=>toast('此版本為共用分析員工作區，帳號功能尚未啟用');
window.addEventListener('storage',event=>{if(event.key==='echoSaved'){updateSavedCount();render();if(!document.querySelector('#savedModal').hidden)renderSaved()}if(event.key==='echoTopicsV2')renderTopics()});

renderTopics();updateSavedCount();if(isFileMode){statusBox.hidden=false;statusBox.textContent='目前是離線檔案預覽；即時搜尋需要由網站伺服器提供，請使用部署完成的 HTTPS 公開網址。'}
